version: "3.9"
services:
  dev:
    build:
      dockerfile: ./Dockerfile.dev
    image: blog-belgacem-io:0.3
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app